server:
  port: 9191
spring:
  zipkin:
    base-url: http://localhost:9411/
  h2:
    console:
      enabled: true
  application:
    name: PAYMENT-SERVICE
logging:
  file:
    name: D:\Al-TP9\logs\microservice.log